language: node_js
node_js:
  - '16'
branches:
  only:
    - master
cache:
  directories:
    - xylsh_blog_source/node_modules
before_install:
  - rm -rf xylsh_blog_source
  - git clone  https://github.com/weizhimiao/xylsh_blog_source.git xylsh_blog_source --recursive
  - cd xylsh_blog_source
#  - git submodule foreach git pull origin master
  - cd article && git pull origin master && cd ..
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo clean
  - hexo algolia
  - hexo generate --silent

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: xylsh_blog_source/docs
  repo: weizhimiao/weizhimiao.github.io
  target_branch: gh-pages
  keep_history: false
  project_name: xylsh
  email: zhimiao2008@gmail.com
  name: zhimiao
  committer_from_gh: false
  allow_empty_commit: true
  verbose: true
  on:
    branch: master

